FROM python:3-alpine

## install ansible
ENV ANSIBLE_VERSION=2.7.6

RUN set -xe \
    && echo "****** Install system dependencies ******" \
    && apk update \
    && apk add --no-cache bash --progress openjdk8 subversion \
        curl wget coreutils tini sudo \
        python py-pip openssl \
        ca-certificates git openssh sshpass \
    && apk --update add --virtual build-dependencies \
        python-dev libffi-dev openssl-dev build-base \
    \
    && echo "****** Install ansible and python dependencies ******" \
    && pip install --upgrade pip \
    && pip install ansible==${ANSIBLE_VERSION} boto boto3 \
    \
    && echo "****** Remove unused system librabies ******" \
    && apk del build-dependencies \
    && rm -rf /var/cache/apk/*

RUN set -xe \
    && mkdir -p /etc/ansible \
    && echo -e "[local]\nlocalhost ansible_connection=local" > \
        /etc/ansible/hosts


## Add Jenkins user
ARG user=jenkins
ARG group=jenkins
ARG uid=1000
ARG gid=1000
ARG JENKINS_AGENT_HOME=/home/${user}

ENV JENKINS_AGENT_HOME ${JENKINS_AGENT_HOME}

RUN set -xe \
    && echo "****** Add jenkins user and goupe ******" \
    && addgroup -g ${gid} ${group} \
    && adduser -h "${JENKINS_AGENT_HOME}" -u "${uid}" -G "${group}" -s /bin/bash -D "${user}"\
    && passwd -u jenkins &&  mkdir ${JENKINS_AGENT_HOME}/.ssh

# setup SSH server
RUN set -xe \
    && echo "****** setup SSH server ******" \
    && sed -i /etc/ssh/sshd_config \
        -e 's/#PermitRootLogin.*/PermitRootLogin no/' \
        -e 's/#RSAAuthentication.*/RSAAuthentication yes/'  \
        -e 's/#PasswordAuthentication.*/PasswordAuthentication no/' \
        -e 's/#SyslogFacility.*/SyslogFacility AUTH/' \
        -e 's/#LogLevel.*/LogLevel INFO/' \
    && mkdir /var/run/sshd

VOLUME "${JENKINS_AGENT_HOME}" "/tmp" "/run" "/var/run"
WORKDIR "${JENKINS_AGENT_HOME}"

COPY setup-ssh-keys /usr/local/bin/setup-ssh-keys
COPY "*.pub" "${JENKINS_AGENT_HOME}/.ssh"

EXPOSE 22

ENTRYPOINT ["setup-ssh-keys"]
